pirate_speak:
  llm: openai
  agent: langserve
  display_name: Pirate Speak
  avatar_url: https://avatars.githubusercontent.com/u/126733545?s=48&v=4
  description: A Langserve demo using a demo [Langchain Template](https://templates.langchain.com/) that will repeat back what you say but in a pirate accent.  Ooh argh me hearties!  Langchain templates cover many different GenAI use cases and all can be streamed to Multivac clients.
  secrets:
    - OPENAI_API_KEY
csv_agent:
  llm: openai
  agent: langserve
  display_name: Titanic
  avatar_url: https://avatars.githubusercontent.com/u/126733545?s=48&v=4
  description: A Langserve demo using a demo [Langchain Template](https://templates.langchain.com/) that lets you ask questions over structured data like a database.  In this case, a local database contains statistics from the Titanic disaster passengers.  Langchain templates cover many different GenAI use cases and all can be streamed to Multivac clients.
  secrets:
    - OPENAI_API_KEY
rag_lance:
  llm: openai
  agent: langserve
  display_name: Simple RAG
  avatar_url: https://avatars.githubusercontent.com/u/126733545?s=48&v=4
  description: A Langserve demo using a demo [Langchain Template](https://templates.langchain.com/) that lets you ask questions over unstructured data.
  memory:
    - lancedb-vectorstore:
        vectorstore: lancedb
        provider: LanceDB 
  secrets:
      - OPENAI_API_KEY
