pirate_speak:
  llm: openai
  agent: langserve
  display_name: Pirate Speak
  tags: ["free"]
  avatar_url: https://avatars.githubusercontent.com/u/126733545?s=48&v=4
  description: A Langserve demo using a demo [Langchain Template](https://templates.langchain.com/) that will repeat back what you say but in a pirate accent.  Ooh argh me hearties!  Langchain templates cover many different GenAI use cases and all can be streamed to Multivac clients.
  secrets:
    - OPENAI_API_KEY
csv_agent:
  llm: openai
  agent: langserve
  display_name: Titanic
  tags: ["free"]
  avatar_url: https://avatars.githubusercontent.com/u/126733545?s=48&v=4
  description: A Langserve demo using a demo [Langchain Template](https://templates.langchain.com/) that lets you ask questions over structured data like a database.  In this case, a local database contains statistics from the Titanic disaster passengers.  Langchain templates cover many different GenAI use cases and all can be streamed to Multivac clients.
  secrets:
    - OPENAI_API_KEY
rag_lance:
  llm: openai
  agent: langserve
  display_name: Simple RAG
  tags: ["free"]
  avatar_url: https://avatars.githubusercontent.com/u/126733545?s=48&v=4
  description: A Langserve demo using a demo [Langchain Template](https://templates.langchain.com/) that lets you ask questions over unstructured data.
  memory:
    - lancedb-vectorstore:
        vectorstore: lancedb
        provider: LanceDB 
  secrets:
      - OPENAI_API_KEY
image_talk:
  llm: vertex
  model: gemini-1.0-pro-vision
  agent: langserve
  upload: 
    mime_types:
      - image
  display_name: Talk to Images
  tags: ["free"]
  avatar_url: https://avatars.githubusercontent.com/u/1342004?s=200&v=4
  description: A picture is worth a thousand words, so upload your picture and ask your question to the Gemini Pro Vision model.  Images are remembered for your conversation until you upload another.  This offers powerful applications, which you can get a feel for via the [Gemini Pro Vision docs](https://cloud.google.com/vertex-ai/docs/generative-ai/multimodal/design-multimodal-prompts) 
eduvac:
  llm: anthropic
  model: claude-3-opus-20240229
  agent: eduvac # needs to match multivac service name
  agent_type: langserve
  display_name: Edu-VAC
  tags: ["eduvac"]
  avatar_url: ../public/eduvac.png
  description: Educate yourself in your own personal documents via guided learning from Eduvac, the ever patient teacher bot. Use search filters to examine available syllabus or upload your own documents to get started.
  upload:   # to accept uploads of private documents to a bucket
    mime_types:
      - all
    buckets:
      all: your-bucket
  buckets:
    raw: your-bucket
  docstore: # this needs to be valid to have document storage
    - alloydb-docstore:
        type: alloydb
  alloydb_config:
    project_id: your-projectid
    region: europe-west1
    cluster: your-cluster
    instance: primary-instance-1